### PR TITLE
add option to use predefined set(s) of permutation(s)

### PR DESCRIPTION
**Pull request by andrazmatkovic**
I've added option to use predefined set(s) of permutation(s) (e.g. which can be created using palm_quickperms.m function).

### CODE REVIEW

**Comment by andersonwinkler** [comment]
Hi Andraz, did you close because there is an issue with the branch? I didn't have a chance of reviewing yet...

**Comment by andrazmatkovic** [comment]
Hi, there is no issue with the branch, I merged it with master. I can make
new pull request if needed.

V V sre., 13. jan. 2021 ob 16:47 je oseba A. M. Winkler <
notifications@github.com> napisala:

**Comment by andersonwinkler** [comment]
got it, thanks!

**Comment by andersonwinkler** [comment]
Hi Andraz,
I don't seem to be able to reopen the PR... the button is grayed out. I wonder if this isn't because it was deleted?
If you can reopen, that would be great, otherwise I'll work from scratch. Either way is fine for me.
Thanks!
Anderson

**Comment by andrazmatkovic** [comment]
Hi, I cannot reopen the PR, because the branch was deleted. You can still see the commits here: https://github.com/andersonwinkler/PermCCA/pull/4/commits

**Comment by andersonwinkler** [comment]
Hi Andraz,

Ok, no problem, thanks.

I've just committed an update to add the feature. Your code was fine, however, it was permuting both Y and X; if the permutation set happened to be the same for both (e.g., because the same seed was used for the random number generator), then permutations would be symmetric for both sides, leading to no net change. The main difference is that in the current code only one side is ever shuffled, whereas the other remains fixed.

Also, the dimensionality reduction is left out for now (we'll have another tool for this coming out soon, that will do other interesting things; it's being written up).

Thanks again!

Anderson

**Comment by andrazmatkovic** [comment]
Ok, thanks for letting me know. I've made some additional changes in my
cloned repo (https://github.com/andrazmatkovic/PermCCA) for my use, but
they are probably not relevant for you.

V V pon., 19. apr. 2021 ob 16:59 je oseba A. M. Winkler <
***@***.***> napisala:

**Pull request closed without merging**
